/// 
Class SourceControl.Git.ADTFromPartyprc Extends Ens.Rule.Definition
{

Parameter RuleAssistClass = "EnsLib.MsgRouter.VDocRuleAssist";

XData RuleDefinition [ XMLNamespace = "http://www.intersystems.com/rule" ]
{
<ruleDefinition alias="SourceControl.Git.ADTFromParty_prc" context="EnsLib.MsgRouter.VDocRoutingEngine" production="SourceControl.CPHL7">
<ruleSet name="" effectiveBegin="" effectiveEnd="">
<rule name="">
</rule>
</ruleSet>
</ruleDefinition>
}

}

